### ISSUE TITLE
Usage Help

### ISSUE THREAD

**Issue by olaban-ji** [jiaweihli/manga_downloader#92]
I'm Kind Of New To This Python Of A Thing. I'd Like To Know How To Install/run This Script. I'd Appreciate The Help.

**Comment by ashura0** [comment]
Well, you didn't specify whether you wanted to use on Linux or Windows. In Linux, python is  preinstalled, so open terminal (or konsole or whatever), go to the directory (in the terminal) you have downloaded and extracted the manga_downloader. Type "python manga.py ". This should display some help message. See https://github.com/jiaweihli/manga_downloader#usage and https://github.com/jiaweihli/manga_downloader#options for more.
In windows, you have to install python from http://python.org . Take care to install 2.7+ version, so as to support this program. You then have to again open the terminal, in windows its called command prompt/ cmd, go to the extracted folder in cmd and type " python manga.py". This will also display some help. Again refer the Usage and Options for this program. Happy Downloading...

**Comment by olaban-ji** [comment]
Thanks For The Help. It's A Windows System. By The  'Python 2.7+' You Stated, Does It Include Python 3.6.1 (That's The Version Of Python I Run On My System)? Also I Was Thinking Of Adding The Script's Location/directory To PATH Variable?

**Comment by ashura0** [comment]
No, python 3.xx and 2.xx are two different versions. The reason I said 2.7 is because the program is written predominantly in 2.7 format/whatever. If you're using 3.x it may break. 
" Also I Was Thinking Of Adding The Script's Location/directory To PATH Variable?" 
You could do that, idk much about adding PATH variables ^_^ ( I use mainly Linux). Google it, you will get a solution...

**Comment by olaban-ji** [comment]
Thanks For The Info.

**Comment by jklmli** [comment]
Thanks @ashura0 for helping out!
